### ISSUE TITLE
Can you port this library to Dart?

### ISSUE THREAD

**Issue by Emasoft** [jasonmayes/Smart-Content-Placer#1]
This lib is amazing, can you port it natively in Dart? I'm working on several projects that would need something like that, and they must be all in native Dart.

**Comment by jasonmayes** [comment]
Thank you for the kind comment. Unfortunately I do not use Dart myself. If there is enough interest maybe as a community we can put something together. Feel free to fork, create a dart folder, and make a pull request when ready if you wish to give it a go yourself. If it works out well we can merge that for others to use.
